version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_biblioteca
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: biblioteca_db
      POSTGRES_USER: biblioteca_user
      POSTGRES_PASSWORD: biblioteca_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
